# Bar, wallpaper
# exec-once = swww-daemon --format xrgb --no-cache
# exec-once = sleep 0.5; swww img "$(cat ~/.local/state/quickshell/user/generated/wallpaper/path.txt)" --transition-step 100 --transition-fps 120 --transition-type grow --transition-angle 30 --transition-duration 1
# exec-once = ~/.config/hypr/hyprland/scripts/start_geoclue_agent.sh & gammastep

# Input method
# exec-once = fcitx5

# Core components (authentication, lock screen, notification daemon)
# exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = /usr/lib/polkit-kde-authentication-agent-1 || /usr/libexec/polkit-kde-authentication-agent-1  || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1
# exec-once = hypridle
# exec-once = dbus-update-activation-environment --all
# exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
# exec-once = hyprpm reload

# Audio
# exec-once = easyeffects --gapplication-service

# ──────────────────────────────────────────────────────────────────────

# Keyring and auth
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = systemctl --user start hyprpolkitagent

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Cursors
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Location provider and night light
exec-once = /usr/lib/geoclue-2.0/demos/agent
# exec-once = sleep 1 && gammastep
exec-once = hyprsunset

# Idle inhibit when audio playing
exec-once = sway-audio-idle-inhibit --ignore-source-outputs cava

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Resize and move windows based on matches (e.g. pip)
exec-once = caelestia resizer -d

# Reload hyprland when config changes (to regenerate everything)
# exec-once = $hypr/scripts/monitor-config.fish

# Detect display config changes
exec-once = $hypr/scripts/display-profiles.fish

# Start shell
# exec-once = caelestia shell -d
exec-once = qs -c $qsConfig &

# Wallpaper
# exec-once = hyprpaper

# Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &

# Idle daemon
exec-once = hypridle

# KDEConnect
exec-once = kdeconnectd
exec-once = kdeconnect-indicator
