# See https://wiki.hyprland.org/Configuring/Binds/

exec = hyprctl dispatch submap global
submap = global

# ╭───────────────────────────────────────────────────────────╮
# │                         Launcher                          │
# ╰───────────────────────────────────────────────────────────╯
# WARNING: These absolutely need to be on top, or they won't work consistently
# bindi = SUPER, Super_L, global, $qsConfig:launcher
# bindin = SUPER, catchall, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse:272, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse:273, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse:274, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse:275, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse:276, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse:277, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse_up, global, $qsConfig:launcherInterrupt
# bindin = SUPER, mouse_down, global, $qsConfig:launcherInterrupt

# bind = SUPER, T, exec, app2unit -- ghostty
# bind = SUPER, W, exec, app2unit -- vivaldi
# bind = SUPER SHIFT, W, exec, app2unit -- zen-browser
# bind = SUPER, C, exec, app2unit -- zeditor
# bind = SUPER, G, exec, app2unit -- ghostty -e lazygit
# bind = SUPER, E, exec, app2unit -- dolphin
# bind = SUPER ALT, E, exec, app2unit -- thunar
# bind = Ctrl+Alt, Escape, exec, app2unit -- qps
# bind = Ctrl+Alt, Escape, exec, app2unit -- missioncenter
# bind = Ctrl+Alt, V, exec, app2unit -- pavucontrol

# Application bindings
# $terminal = uwsm app -- alacritty
$terminal = app2unit -- ghostty
$browser = omarchy-launch-browser

# bindd = SUPER, return, Terminal, exec, $terminal --working-directory=$(omarchy-cmd-terminal-cwd)
# bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
# bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, RETURN, Terminal, exec, $terminal
bindd = SUPER, F, File manager, exec, app2unit -- dolphin
bindd = SUPER, B, Browser, exec, app2unit -- vivaldi
# bindd = SUPER, M, Music, exec, app2unit -- youtube-music
bindd = SUPER, N, Neovim, exec, $terminal -e nvim
bindd = SUPER SHIFT, N, Notes (obsidian-nvim), exec, $terminal -e nvim ~/obsidian-vault
bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
# bindd = SUPER, T, Activity, exec, $terminal -e btop
# bindd = SUPER, G, Signal, exec, uwsm app -- signal-desktop
# bindd = SUPER, O, Obsidian, exec, uwsm app -- obsidian -disable-gpu
# bindd = SUPER, slash, Passwords, exec, uwsm app -- 1password

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
$launch_webapp = $hyprland/scripts/launch-webapp.sh
bindd = SUPER, A, ChatGPT, exec, $launch_webapp "https://chatgpt.com"
bindd = SUPER SHIFT, A, Grok, exec, $launch_webapp "https://grok.com"
bindd = SUPER, C, Calendar, exec, $launch_webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER, E, Email, exec, $launch_webapp "https://app.hey.com"
bindd = SUPER, Y, YouTube, exec, $launch_webapp "https://youtube.com/"
bindd = SUPER SHIFT, G, WhatsApp, exec, $launch_webapp "https://web.whatsapp.com/"
# bindd = SUPER ALT, G, Google Messages, exec, omarchy-launch-webapp "https://messages.google.com/web/conversations"
# bindd = SUPER, X, X, exec, $launch_webapp "https://x.com/"
# bindd = SUPER SHIFT, X, X Post, exec, $launch_webapp "https://x.com/compose/post"

# Special workspaces
bindd = SUPER, S, Toggle special workspace, exec, caelestia toggle specialws
bindd = CTRL SHIFT, ESCAPE, Open system monitor app, exec, caelestia toggle sysmon
bindd = SUPER, M, Open music player app, exec, caelestia toggle music
bindd = SUPER, D, Open communication app, exec, caelestia toggle communication
bindd = SUPER, T, Open todo app, exec, caelestia toggle todo

source = $hyprland/bindings/utilities.conf
source = $hyprland/bindings/tiling.conf
source = $hyprland/bindings/media.conf
