[General]
AdditionalQmlImportPaths=modules
DisableDefaultImports=false
; OverwriteImportTypes=
; ResourcePath=
MaxWarnings=0

[Warnings]
BadSignalHandler=warning
Deprecated=warning
ImportFailure=disable
InheritanceCycle=warning
MultilineStrings=info
MissingProperty=disable
PropertyAlias=warning
RequiredProperty=warning
TypeError=disable
UnknownProperty=warning
UnqualifiedAccess=disable
UnresolvedType=disable
UnusedImports=info
WithStatement=warning
Import=disable
