# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

# input {
#     follow_mouse = 2 # 0|1|2|3
#     float_switch_override_focus = 2
# }
input {
    kb_layout = us
    kb_variant = altgr-intl
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.5
    }
}
