input {
    kb_layout = us
    kb_variant = altgr-intl
    # TODO: make a script to change this when gaming
    kb_options = caps:swapescape 
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35
    
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.5
    }
}
