# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 CachyOS Hyprland Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER
$hypr = ~/.config/hypr/hyprland

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = $hypr/animations.conf
source = $hypr/autostart.conf
source = $hypr/decorations.conf
source = $hypr/environment.conf
source = $hypr/input.conf
source = $hypr/keybinds.conf
source = $hypr/monitors.conf
source = $hypr/variables.conf
source = $hypr/rules.conf

# Modifying these configs can be done by creating a user defined config in the home directory, e.g.
## ~/.config/hypr/config/user-config.conf
# source = ~/.config/hypr/config/user-config.conf
