# ╭───────────────────────────────────────────────────────────╮
# │                  Hyprland Configuration                   │
# ╰───────────────────────────────────────────────────────────╯

$mainMod = SUPER
$hypr = ~/.config/hypr
$hyprland = $hypr/hyprland
$qsConfig = caelestia

source = $hyprland/animations.conf
source = $hyprland/colors.conf
source = $hyprland/decoration.conf
source = $hyprland/env.conf
source = $hyprland/execs.conf
source = $hyprland/general.conf
source = $hyprland/input.conf
source = $hyprland/keybinds.conf
source = $hyprland/monitors.conf
source = $hyprland/rules.conf
