# ╭───────────────────────────────────────────────────────────╮
# │                  Hyprland Configuration                   │
# ╰───────────────────────────────────────────────────────────╯

exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work


$mainMod = SUPER
$hypr = ~/.config/hypr/hyprland

source = $hypr/animations.conf
source = $hypr/colors.conf
source = $hypr/decoration.conf
source = $hypr/env.conf
source = $hypr/execs.conf
source = $hypr/general.conf
source = $hypr/input.conf
source = $hypr/keybinds.conf
source = $hypr/monitors.conf
source = $hypr/rules.conf
