# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/


input {
    kb_layout = us
    kb_variant = altgr-intl
}

cursor {
    hide_on_key_press = true
}
