# Steam
windowrule = rounding 10, title:, class:steam
windowrule = float, title:Friends List, class:steam
windowrule = immediate, class:steam_app_[0-9]+  # Allow tearing for steam games
windowrule = idleinhibit always, class:steam_app_[0-9]+  # Always idle inhibit when playing a steam game

windowrule = workspace 10, class:steam # Open steam in workspace 10
windowrule = center, class:steam, title:Friends List
windowrule = opacity 1 1, class:steam

# ATLauncher console
windowrule = float, class:com-atlauncher-App, title:ATLauncher Console
