# Picture-in-picture overlays
windowrule = tag +pip, title:(Picture.{0,1}in.{0,1}[Pp]icture)
windowrule = float, tag:pip
windowrule = pin, tag:pip
windowrule = size 600 338, tag:pip
windowrule = keepaspectratio, tag:pip
windowrule = noborder, tag:pip
windowrule = opacity 1 1, tag:pip
windowrule = move 100%-w-40 4%, tag:pip

# Picture in picture (resize and move done via script)
# windowrule = move 100%-w-2% 100%-w-3%, title:Picture(-| )in(-| )[Pp]icture  # Initial move so window doesn't shoot across the screen from the center
# windowrule = keepaspectratio, title:Picture(-| )in(-| )[Pp]icture
# windowrule = float, title:Picture(-| )in(-| )[Pp]icture
# windowrule = pin, title:Picture(-| )in(-| )[Pp]icture
