alias omzconfig="cd ~/.oh-my-zsh/custom && nvim"
alias zshconfig="cd ~/.zshrc && nvim"
alias nvimconfig="cd ~/.config/nvim && nvim"
alias p="pnpm"
alias aliases="cd ~/.oh-my-zsh/custom && nvim aliases.zsh"
alias vault="cd ~/obsidian-vault && nvim"
