# alias omzconfig="nvim ~/.oh-my-zsh/custom"
alias omzconfig="cd ~/.oh-my-zsh/custom && nvim"
# alias zshconfig="nvim ~/.zshrc"
alias zshconfig="cd ~/.zshrc && nvim"
# alias nvimconfig="nvim ~/.config/nvim"
alias nvimconfig="cd ~/.config/nvim && nvim"
alias p="pnpm"
alias aliases="nvim ~/.oh-my-zsh/custom/aliases.zsh"
# alias aliases="cd ~/.oh-my-zsh/custom && nvim aliases.zsh"
# alias vault="nvim ~/obsidian-vault"
alias vault="cd ~/obsidian-vault && nvim"
alias astronvim="NVIM_APPNAME=astronvim nvim"
alias omzr="omz reload"
